pipeline {
    agent any
    
    stages {
        stage('Hello World') {
            steps {
                echo 'Hello, World!'
                echo 'This is a basic Jenkins pipeline'
            }
        }
    }
}

